# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Grove < Formula
  desc "Terminal UI for Git worktrees"
  homepage "https://github.com/henri123lemoine/grove"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/henri123lemoine/grove/releases/download/v0.1.5/grove_0.1.5_darwin_x86_64.tar.gz"
      sha256 "320cbc176915c0f7aeeeb225187d9dcc289a506b88503c52515c7053cb12bf55"

      def install
        bin.install "grove"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/henri123lemoine/grove/releases/download/v0.1.5/grove_0.1.5_darwin_arm64.tar.gz"
      sha256 "15fe9e70f9646a0dbd24e91fa19eb7704f3e96695b9b956098bcf6ae5d156529"

      def install
        bin.install "grove"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/henri123lemoine/grove/releases/download/v0.1.5/grove_0.1.5_linux_x86_64.tar.gz"
      sha256 "fa6acbb8422346085c944241d588e72886c91a2b88c640cd63b5eb94ced52939"
      def install
        bin.install "grove"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/henri123lemoine/grove/releases/download/v0.1.5/grove_0.1.5_linux_arm64.tar.gz"
      sha256 "8058c53decde858ae126097b02a667bf8337df69e633a5ea0a57f6e63e84bbc9"
      def install
        bin.install "grove"
      end
    end
  end

  test do
    system "#{bin}/grove", "--version"
  end
end
